site_name: 'SpankPay Developer Documentation'
repo_name: 'spankchain/docs.spankpay.com'
repo_url: 'https://github.com/spankchain/docs.spankpay.com'
site_description: 'SpankPay Developer Documentation'
nav:
    - Home: 'index.md'
    - API Reference: 'api-reference.md'

theme:
  name: 'material'
  palette:
        primary: 'pink'
        accent: 'purple'
  logo: 'images/white-S-logo.png'
  favicon: 'images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences

extra:
  social:
    - type: 'github'
      link: 'https://github.com/spankchain'
    - type: 'medium'
      link: 'https://www.medium.com/spankchain'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/SpankChain/'
    - type: 'twitter'
      link: 'https://twitter.com/SpankChain'
    
